---
version: "3.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Warsaw
    volumes:
      - /home/server/media-server/Configurations/Jellyfin:/config
      - /home/server/media-server/Storage/Media:/data
    ports:
      - "5121:8096"
    restart: unless-stopped
