---
version: "3.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Warsaw
    volumes:
      - /home/server/media-server/Configurations/Lidarr:/config
      - /home/server/media-server/Storage/Downloads:/downloads
      - /home/server/media-server/Storage/Music:/music
    ports:
      - "5341:8686"
    restart: unless-stopped