---
version: "3.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /home/server/media-server/Configurations/Plex:/config
      - /home/server/media-server/Storage/Media:/media
    ports:
      - "5111:32400"
    restart: unless-stopped