---
version: "3.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Warsaw
    volumes:
      - /home/server/media-server/Configurations/Readarr:/config
      - /home/server/media-server/Storage/Downloads:/downloads
      - /home/server/media-server/Storage/Library/Books:/books
    ports:
      - "5351:8787"
    restart: unless-stopped
