---
version: "3.1"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8265:8265" # webUI port
      - "8266:8266" # server port
      - "8267:8267" # Internal node port
      - "8268:8268" # Example extra node port
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Warsaw
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
    volumes:
      - /home/server/media-server/Configurations/Tdarr:/app/configs
      - /home/server/media-server/Storage/Media:/media
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Warsaw
      - nodeID=MainNode
      - serverIP=0.0.0.0
      - serverPort=8266
    volumes:
      - /home/server/media-server/Configurations/Tdarr:/app/configs
      - /home/server/media-server/Storage/Media:/media